const IDEA_COLLECTIONS = [
  {
    niche: "Creator Education",
    audience: "Attract",
    goals: ["Grow Audience", "Build Authority"],
    ideas: [
      {
        title: "30-Day Creator Reset Blueprint",
        description:
          "Map a full month of practical prompts that help overwhelmed creators restart with structure.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["challenge", "planning", "consistency", "reset"],
        featured: true,
        uniquenessScore: 95,
      },
      {
        title: "Beginner Creator FAQ Reel",
        description:
          "Answer the five questions new creators repeat most often in a quick, highly savable short.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["beginner", "faq", "reels", "education"],
        featured: false,
        uniquenessScore: 82,
      },
      {
        title: "From Zero to 1K: Creator Roadmap",
        description:
          "Break the early creator journey into a clearer sequence of skills, milestones, and priorities.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 35,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["roadmap", "growth", "beginner", "milestones"],
        featured: true,
        uniquenessScore: 94,
      },
      {
        title: "The Advice I Ignore Now",
        description:
          "Use strong opinions to explain which common creator tips stop being useful after the basics.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 10,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["opinion", "creator myths", "hooks", "clarity"],
        featured: false,
        uniquenessScore: 85,
      },
      {
        title: "Weekly Creator Debrief Newsletter",
        description:
          "Share one experiment, one mistake, and one next move to build trust through visible iteration.",
        format: "Newsletter",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Nurture",
        goals: ["Build Authority", "Improve Consistency"],
        tags: ["newsletter", "reflection", "systems", "trust"],
        featured: false,
        uniquenessScore: 76,
      },
      {
        title: "Tutorial Hell Recovery Plan",
        description:
          "Explain how to stop endlessly learning and start creating using a smaller execution loop.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["learning", "execution", "mindset", "creator block"],
        featured: false,
        uniquenessScore: 84,
      },
      {
        title: "How I Got Everything I Want From the Internet",
        description:
          "Use a bold personal-story angle to show how leverage, taste, distribution, and compounding trust changed your creator life.",
        format: "YouTube",
        difficulty: "High",
        filmingMinutes: 55,
        editingEffort: "High",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["future", "skills", "career", "education"],
        featured: true,
        uniquenessScore: 100,
      },
      {
        title: "Film With Me: One Hour Content Sprint",
        description:
          "Take viewers through a realistic one-hour sprint so the process feels more achievable.",
        format: "Live",
        difficulty: "Medium",
        filmingMinutes: 45,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        audience: "Nurture",
        goals: ["Improve Consistency", "Increase Engagement"],
        tags: ["batching", "live", "workflow", "behind the scenes"],
        featured: false,
        uniquenessScore: 88,
      },
      {
        title: "One Concept, Five Angles",
        description:
          "Show how a single teaching point can become multiple posts instead of chasing new ideas daily.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        goals: ["Grow Audience", "Improve Consistency"],
        tags: ["angles", "repurposing", "idea system", "teaching"],
        featured: false,
        uniquenessScore: 83,
      },
      {
        title: "Mini Case Study: Simplify to Grow",
        description:
          "Walk through a creator example where fewer formats and clearer positioning led to better momentum.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 30,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["case study", "simplify", "positioning", "growth"],
        featured: false,
        uniquenessScore: 87,
      },
    ],
  },
  {
    niche: "YouTube Growth",
    audience: "Attract",
    goals: ["Grow Audience", "Build Authority"],
    ideas: [
      {
        title: "Thumbnail Teardown in Public",
        description:
          "Review weak thumbnails and explain the changes that would improve click-through at a glance.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 35,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["thumbnail", "ctr", "audit", "youtube"],
        featured: true,
        uniquenessScore: 94,
      },
      {
        title: "Why Nobody Cares Until This One Thing Changes",
        description:
          "Break down the first packaging shift that makes a tiny channel suddenly easier to notice, click, and remember.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 40,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["small channel", "audit", "growth", "strategy"],
        featured: true,
        uniquenessScore: 98,
      },
      {
        title: "Why Good Videos Still Die",
        description:
          "Separate video quality from packaging, topic demand, and distribution so creators diagnose better.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 10,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["distribution", "packaging", "failure analysis", "mindset"],
        featured: false,
        uniquenessScore: 86,
      },
      {
        title: "Search vs Suggested Cheat Sheet",
        description:
          "Explain which video ideas work better for YouTube search and which belong in browse and suggested.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["search", "suggested", "seo", "strategy"],
        featured: false,
        uniquenessScore: 88,
      },
      {
        title: "Three Titles I'd Test for This Topic",
        description:
          "Show alternate title framings for the same topic so viewers learn packaging tradeoffs in context.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["titles", "testing", "hooks", "youtube"],
        featured: false,
        uniquenessScore: 84,
      },
      {
        title: "My Retention Checkpoints",
        description:
          "Share the specific moments in a video you inspect first when figuring out where viewers dropped off.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 30,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Nurture",
        goals: ["Build Authority", "Increase Engagement"],
        tags: ["retention", "analytics", "youtube", "watch time"],
        featured: false,
        uniquenessScore: 83,
      },
      {
        title: "Packaging Makeover Live",
        description:
          "Redo a title and thumbnail set live so the audience can watch the reasoning in real time.",
        format: "Live",
        difficulty: "Medium",
        filmingMinutes: 45,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: false,
        audience: "Nurture",
        goals: ["Increase Engagement", "Build Authority"],
        tags: ["live audit", "packaging", "youtube", "community"],
        featured: false,
        uniquenessScore: 89,
      },
      {
        title: "Channel Banner Audit",
        description:
          "Use quick before-and-after examples to show how weak channel banners confuse first-time visitors.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["banner", "branding", "channel page", "clarity"],
        featured: false,
        uniquenessScore: 74,
      },
      {
        title: "Three Series Better Than Random Uploads",
        description:
          "Pitch more strategic repeatable series ideas that make a channel easier to understand and follow.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        goals: ["Grow Audience", "Improve Consistency"],
        tags: ["series", "consistency", "channel strategy", "repeatable"],
        featured: false,
        uniquenessScore: 85,
      },
      {
        title: "Intro Rewrite Challenge",
        description:
          "Take one weak opening and rewrite it three ways to improve curiosity, clarity, and stakes.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["intro", "rewrite", "hooks", "retention"],
        featured: false,
        uniquenessScore: 87,
      },
    ],
  },
  {
    niche: "Short-Form Strategy",
    audience: "Attract",
    goals: ["Grow Audience", "Increase Engagement"],
    ideas: [
      {
        title: "I Stopped Chasing Views and Everything Changed",
        description:
          "Turn a counterintuitive confession into a short-form lesson about why stronger angles outperform desperate posting volume.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["hooks", "carousel", "reels", "angles"],
        featured: true,
        uniquenessScore: 97,
      },
      {
        title: "Short-Form Scorecard",
        description:
          "Give creators a checklist for rating clarity, pacing, replay value, and takeaway strength.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        audience: "Nurture",
        goals: ["Increase Engagement", "Build Authority"],
        tags: ["scorecard", "retention", "checklist", "shorts"],
        featured: false,
        uniquenessScore: 88,
      },
      {
        title: "Trend to Teaching Angle",
        description:
          "Use a current format or audio as a starting point and then pivot it into original educational value.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 15,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["trends", "teaching", "reels", "originality"],
        featured: true,
        uniquenessScore: 95,
      },
      {
        title: "Comment-to-Content Machine",
        description:
          "Turn repeated questions in the comments into a repeating system for practical weekly posts.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        audience: "Nurture",
        goals: ["Increase Engagement", "Improve Consistency"],
        tags: ["comments", "community", "ideas", "consistency"],
        featured: false,
        uniquenessScore: 86,
      },
      {
        title: "7-Day Reels Sprint Plan",
        description:
          "Outline a realistic one-week publishing challenge with a theme, hook type, and CTA for each day.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        goals: ["Improve Consistency", "Grow Audience"],
        tags: ["challenge", "reels", "plan", "execution"],
        featured: false,
        uniquenessScore: 84,
      },
      {
        title: "B-Roll Library for Talking-Head Posts",
        description:
          "Show a reusable shot list that keeps talking-head shorts from looking repetitive and static.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 20,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: true,
        tags: ["b-roll", "visuals", "talking head", "workflow"],
        featured: false,
        uniquenessScore: 80,
      },
      {
        title: "Why This Hook Earned Replays",
        description:
          "Break down a short-form opening that works because it creates tension and clarity at the same time.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 28,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["hooks", "analysis", "replays", "retention"],
        featured: false,
        uniquenessScore: 89,
      },
      {
        title: "Three CTA Styles That Still Feel Human",
        description:
          "Teach call-to-action structures that create movement without sounding needy or scripted.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: true,
        goals: ["Increase Engagement", "Sell Offer"],
        audience: "Convert",
        tags: ["cta", "conversion", "copywriting", "social"],
        featured: false,
        uniquenessScore: 87,
      },
      {
        title: "20-Second Lesson Script Template",
        description:
          "Share a tight script formula for delivering a useful lesson before viewers have time to bounce.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["script", "template", "education", "short-form"],
        featured: false,
        uniquenessScore: 85,
      },
      {
        title: "A Better Series Than Daily Vlogs",
        description:
          "Replace unfocused daily updates with a more strategic recurring format that still feels personal.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 10,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        goals: ["Grow Audience", "Improve Consistency"],
        tags: ["series", "vlogs", "strategy", "repeatable"],
        featured: false,
        uniquenessScore: 83,
      },
    ],
  },
  {
    niche: "Video Editing",
    audience: "Nurture",
    goals: ["Build Authority", "Increase Engagement"],
    ideas: [
      {
        title: "I Edited One Clip 17 Ways and Finally Understood Retention",
        description:
          "Use one raw clip and multiple edit passes to reveal which changes actually make viewers stay longer.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 35,
        editingEffort: "High",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["before after", "editing", "tutorial", "talking head"],
        featured: true,
        uniquenessScore: 96,
      },
      {
        title: "Captions That Do More Than Repeat",
        description:
          "Teach how captions can add emphasis, rhythm, and hierarchy instead of duplicating every spoken word.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["captions", "editing", "retention", "shorts"],
        featured: false,
        uniquenessScore: 84,
      },
      {
        title: "Editing Shortcuts I Wish I Knew Earlier",
        description:
          "Package concrete speed wins into a practical quick-tip format that new editors can try immediately.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 10,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["shortcuts", "premiere", "speed", "workflow"],
        featured: false,
        uniquenessScore: 82,
      },
      {
        title: "Pace Test: When to Cut",
        description:
          "Explain the visual and audio signals you use to decide whether a clip should breathe or move on.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 30,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["pacing", "cuts", "editing", "timing"],
        featured: false,
        uniquenessScore: 81,
      },
      {
        title: "Sound Design for Tiny Wins",
        description:
          "Show how subtle sound effects make educational edits feel more satisfying without becoming noisy.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["sound design", "editing", "audio", "micro moments"],
        featured: false,
        uniquenessScore: 79,
      },
      {
        title: "The Three Zoom Mistakes",
        description:
          "Teach common punch-in errors that make short-form edits feel chaotic instead of intentional.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 10,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["zoom", "editing", "mistakes", "short-form"],
        featured: false,
        uniquenessScore: 80,
      },
      {
        title: "Edit With Me: One Clip Into Three Versions",
        description:
          "Turn a single clip into a polished short, a simple tutorial cut, and a cleaner long-form segment.",
        format: "Live",
        difficulty: "High",
        filmingMinutes: 60,
        editingEffort: "High",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["edit with me", "repurpose", "versions", "workflow"],
        featured: true,
        uniquenessScore: 95,
      },
      {
        title: "My Beginner Editing Checklist",
        description:
          "Offer a step-by-step review list for new editors before they export and publish anything.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["checklist", "beginner", "editing", "quality control"],
        featured: false,
        uniquenessScore: 72,
      },
      {
        title: "The Folder System That Saves Hours",
        description:
          "Show a boring but powerful project structure that makes editing faster once volume goes up.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 25,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["folders", "organization", "workflow", "assets"],
        featured: false,
        uniquenessScore: 78,
      },
      {
        title: "High-Retention Tutorial Cut Pattern",
        description:
          "Break down a tutorial edit structure built around proof, steps, payoff, and recap moments.",
        format: "YouTube",
        difficulty: "High",
        filmingMinutes: 40,
        editingEffort: "High",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["tutorial", "retention", "structure", "editing"],
        featured: false,
        uniquenessScore: 90,
      },
    ],
  },
  {
    niche: "Monetization",
    audience: "Convert",
    goals: ["Sell Offer", "Build Authority"],
    ideas: [
      {
        title: "The First Offer I'd Sell to 300 Followers",
        description:
          "Show how to choose a simple, credible starter offer before building a full product stack.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 35,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["offer", "small audience", "sales", "monetization"],
        featured: true,
        uniquenessScore: 94,
      },
      {
        title: "Pricing Mistakes New Creators Make",
        description:
          "Cover the most common ways creators underprice services, consultations, and brand deliverables.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 40,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["pricing", "services", "revenue", "mistakes"],
        featured: false,
        uniquenessScore: 89,
      },
      {
        title: "Offer Warm-Up Sequence",
        description:
          "Walk through the content sequence that builds desire before you ever drop a sales link.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["launch", "warm up", "offer", "strategy"],
        featured: false,
        uniquenessScore: 86,
      },
      {
        title: "What a High-Converting CTA Sounds Like",
        description:
          "Compare weak CTA language with stronger invitation-based copy that still feels helpful.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["cta", "conversion", "copy", "sales"],
        featured: false,
        uniquenessScore: 84,
      },
      {
        title: "Sponsorship Deck Breakdown",
        description:
          "Show the slides, proof points, and positioning that make a sponsorship deck easier to trust.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 40,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["sponsorship", "deck", "pitch", "brand deals"],
        featured: true,
        uniquenessScore: 93,
      },
      {
        title: "Digital Product Idea Matrix",
        description:
          "Give creators a simple matrix to pick between templates, workshops, guides, and audits.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["digital product", "offer design", "matrix", "ideas"],
        featured: false,
        uniquenessScore: 81,
      },
      {
        title: "Testimonials Into Sales Content",
        description:
          "Turn wins and proof into content that sells by showing the lesson inside the result.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["testimonials", "social proof", "sales", "content"],
        featured: false,
        uniquenessScore: 80,
      },
      {
        title: "Revenue Streams I'd Ignore at the Start",
        description:
          "Use priorities and constraints to explain which monetization paths distract newer creators most.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 10,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["revenue streams", "focus", "monetization", "strategy"],
        featured: false,
        uniquenessScore: 85,
      },
      {
        title: "Soft Sell vs Hard Sell Examples",
        description:
          "Show the tonal difference between subtle conversion content and direct promotional content.",
        format: "Newsletter",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Nurture",
        tags: ["soft sell", "hard sell", "email", "offer"],
        featured: false,
        uniquenessScore: 77,
      },
      {
        title: "Why Tiny Audiences Can Still Buy",
        description:
          "Help creators stop using low follower counts as an excuse not to validate a useful offer.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 28,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["small audience", "sales", "mindset", "offer validation"],
        featured: false,
        uniquenessScore: 88,
      },
    ],
  },
  {
    niche: "Email Marketing",
    audience: "Convert",
    goals: ["Sell Offer", "Build Authority"],
    ideas: [
      {
        title: "Welcome Email Anatomy",
        description:
          "Break down the sections of a welcome email that sets expectations and nudges readers forward.",
        format: "Newsletter",
        difficulty: "Medium",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["welcome email", "email", "conversion", "copywriting"],
        featured: true,
        uniquenessScore: 91,
      },
      {
        title: "Three Lead Magnets for Experts",
        description:
          "Offer lead magnet formats that match expert businesses instead of generic downloadable freebies.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["lead magnet", "experts", "email growth", "offers"],
        featured: false,
        uniquenessScore: 82,
      },
      {
        title: "Newsletter From One Video",
        description:
          "Turn a single long-form video into a structured newsletter without rewriting the whole thing.",
        format: "Newsletter",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Nurture",
        goals: ["Improve Consistency", "Build Authority"],
        tags: ["repurposing", "newsletter", "video", "workflow"],
        featured: false,
        uniquenessScore: 79,
      },
      {
        title: "Subject Line Swipe File",
        description:
          "Share useful subject line patterns by purpose so readers understand why each one works.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["subject lines", "swipe file", "email", "copy"],
        featured: false,
        uniquenessScore: 84,
      },
      {
        title: "Weekly Creator CEO Note",
        description:
          "Use a recurring newsletter frame built around one lesson, one metric, and one next move.",
        format: "Newsletter",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Nurture",
        goals: ["Improve Consistency", "Build Authority"],
        tags: ["newsletter", "reflection", "systems", "creator business"],
        featured: false,
        uniquenessScore: 76,
      },
      {
        title: "Re-Engagement Email That Doesn't Beg",
        description:
          "Write a cleaner reactivation email that feels useful instead of desperate or guilty.",
        format: "Newsletter",
        difficulty: "Medium",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["re-engagement", "email", "list health", "copywriting"],
        featured: false,
        uniquenessScore: 83,
      },
      {
        title: "Launch Week Email Calendar",
        description:
          "Lay out a seven-day launch email rhythm so creators stop guessing when to send what.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["launch", "calendar", "email", "sequence"],
        featured: true,
        uniquenessScore: 90,
      },
      {
        title: "Story Email vs Tip Email",
        description:
          "Compare when a story-led email builds connection and when a tactical email earns clicks faster.",
        format: "Newsletter",
        difficulty: "Medium",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Nurture",
        tags: ["storytelling", "tips", "email", "positioning"],
        featured: false,
        uniquenessScore: 80,
      },
      {
        title: "Link Placement That Gets Clicks",
        description:
          "Show how CTA position changes click behavior in emails without needing a full redesign.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["clicks", "cta placement", "email", "conversion"],
        featured: false,
        uniquenessScore: 85,
      },
      {
        title: "The 5-Minute Newsletter Outline",
        description:
          "Offer a simple structure for drafting a useful newsletter fast enough to stay consistent.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        goals: ["Improve Consistency", "Build Authority"],
        audience: "Nurture",
        tags: ["outline", "newsletter", "writing", "consistency"],
        featured: false,
        uniquenessScore: 78,
      },
    ],
  },
  {
    niche: "Brand Deals",
    audience: "Convert",
    goals: ["Sell Offer", "Build Authority"],
    ideas: [
      {
        title: "What Brands Check Before Replying",
        description:
          "Explain the signals that make creators easier to trust from a sponsor's point of view.",
        format: "Carousel",
        difficulty: "Medium",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["brands", "trust", "sponsorship", "signals"],
        featured: true,
        uniquenessScore: 92,
      },
      {
        title: "Media Kit Mistakes That Cost Replies",
        description:
          "Show why vague metrics and generic positioning make small creators harder for brands to evaluate.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 30,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["media kit", "brand deals", "mistakes", "pitching"],
        featured: false,
        uniquenessScore: 86,
      },
      {
        title: "Brand Deal Pitch Breakdown",
        description:
          "Walk through a real outreach structure that balances confidence, clarity, and proof.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 35,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["pitch", "brand deals", "email", "outreach"],
        featured: true,
        uniquenessScore: 93,
      },
      {
        title: "UGC vs Sponsorship: Which Should You Sell?",
        description:
          "Compare user-generated content work and sponsorship packages so creators pick a cleaner entry point.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["ugc", "sponsorship", "services", "monetization"],
        featured: false,
        uniquenessScore: 87,
      },
      {
        title: "Follow-Up Email Template for Brands",
        description:
          "Teach how to follow up without sounding passive, pushy, or forgettable.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["follow-up", "email", "brands", "template"],
        featured: false,
        uniquenessScore: 79,
      },
      {
        title: "Rate Card Logic for Small Creators",
        description:
          "Show how to build a basic pricing logic before you have perfect benchmarks or huge reach.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 32,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["rate card", "pricing", "brand deals", "small creators"],
        featured: false,
        uniquenessScore: 88,
      },
      {
        title: "Sponsored Content Brief Walkthrough",
        description:
          "Explain the exact information a creator should confirm before filming sponsored deliverables.",
        format: "Carousel",
        difficulty: "Medium",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["brief", "sponsored content", "workflow", "client work"],
        featured: false,
        uniquenessScore: 84,
      },
      {
        title: "Brand Safe Content Checklist",
        description:
          "Give creators a practical review list to avoid risky sponsorship mistakes before publishing.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["brand safe", "checklist", "sponsorship", "quality control"],
        featured: false,
        uniquenessScore: 78,
      },
      {
        title: "How I Track Partnerships in Notion",
        description:
          "Walk through a simple relationship tracker for sponsors, deliverables, and invoicing follow-up.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 35,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Nurture",
        goals: ["Build Authority", "Improve Consistency"],
        tags: ["notion", "crm", "brands", "operations"],
        featured: false,
        uniquenessScore: 81,
      },
      {
        title: "Collab Call Prep for Better Deals",
        description:
          "Share the prep notes and questions that make brand calls smoother and more strategic.",
        format: "Newsletter",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["calls", "prep", "brand deals", "relationships"],
        featured: false,
        uniquenessScore: 77,
      },
    ],
  },
  {
    niche: "Repurposing",
    audience: "Nurture",
    goals: ["Improve Consistency", "Increase Engagement"],
    ideas: [
      {
        title: "One Podcast to Seven Assets",
        description:
          "Show a practical system for turning one long conversation into a full week of content.",
        format: "YouTube",
        difficulty: "High",
        filmingMinutes: 45,
        editingEffort: "High",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["podcast", "repurposing", "systems", "distribution"],
        featured: true,
        uniquenessScore: 94,
      },
      {
        title: "Long Video to Carousel System",
        description:
          "Break one educational video into swipeable points that still make sense on their own.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["carousel", "video", "repurpose", "education"],
        featured: false,
        uniquenessScore: 83,
      },
      {
        title: "Comment Thread to Content Week",
        description:
          "Build a seven-day plan from one active comment section so ideas come from audience language.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["comments", "content week", "ideas", "community"],
        featured: false,
        uniquenessScore: 87,
      },
      {
        title: "Livestream to Newsletter Funnel",
        description:
          "Turn the best moments from a live session into a clear follow-up email with a stronger takeaway.",
        format: "Newsletter",
        difficulty: "Medium",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["livestream", "newsletter", "repurposing", "funnel"],
        featured: false,
        uniquenessScore: 79,
      },
      {
        title: "Behind-the-Scenes Clips You Should Always Grab",
        description:
          "Make batch days more useful by capturing a reusable library of support shots every time.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 15,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: true,
        tags: ["behind the scenes", "b-roll", "workflow", "repurpose"],
        featured: false,
        uniquenessScore: 80,
      },
      {
        title: "Screenshot to Swipe Post",
        description:
          "Use comments, analytics, or drafts screenshots to create more visual educational posts quickly.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: true,
        tags: ["screenshots", "carousel", "visual content", "quick wins"],
        featured: false,
        uniquenessScore: 76,
      },
      {
        title: "Old Video Refresh Checklist",
        description:
          "Refresh strong older videos with new framing instead of assuming every next idea must be new.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["refresh", "evergreen", "content library", "reuse"],
        featured: false,
        uniquenessScore: 78,
      },
      {
        title: "Evergreen Library Board",
        description:
          "Show the simple board you use to store timeless topics worth recycling each quarter.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 28,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        goals: ["Improve Consistency", "Build Authority"],
        tags: ["evergreen", "library", "notion", "systems"],
        featured: true,
        uniquenessScore: 90,
      },
      {
        title: "Turn Testimonials Into Repurposed Proof",
        description:
          "Reuse proof in a more useful way by pairing results with lessons and context.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Convert",
        goals: ["Sell Offer", "Build Authority"],
        tags: ["proof", "testimonials", "sales content", "repurpose"],
        featured: false,
        uniquenessScore: 75,
      },
      {
        title: "Q&A to Content Batch Map",
        description:
          "Show how one audience Q&A can feed shorts, newsletters, and a future longer tutorial.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 30,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["q&a", "batching", "content map", "repurposing"],
        featured: false,
        uniquenessScore: 88,
      },
    ],
  },
  {
    niche: "Creator Systems",
    audience: "Nurture",
    goals: ["Improve Consistency", "Build Authority"],
    ideas: [
      {
        title: "Monday Dashboard I Check First",
        description:
          "Walk through the handful of metrics and to-dos you review before planning the week.",
        format: "Carousel",
        difficulty: "Medium",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["dashboard", "weekly review", "systems", "analytics"],
        featured: true,
        uniquenessScore: 91,
      },
      {
        title: "Content Calendar in 15 Minutes",
        description:
          "Demonstrate a lightweight planning workflow that gets ideas on the calendar without overengineering it.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 15,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["calendar", "planning", "productivity", "content"],
        featured: false,
        uniquenessScore: 84,
      },
      {
        title: "Batch Day Template",
        description:
          "Lay out a repeatable batch-day schedule so creators stop improvising every time they film.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["batching", "template", "filming day", "systems"],
        featured: false,
        uniquenessScore: 79,
      },
      {
        title: "Creator CRM in Notion",
        description:
          "Show the simple database used to track collaborators, sponsors, and follow-up tasks.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 45,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["notion", "crm", "systems", "operations"],
        featured: true,
        uniquenessScore: 90,
      },
      {
        title: "Monthly Reset Checklist",
        description:
          "Give creators an end-of-month review flow to clean up projects and plan the next cycle.",
        format: "Newsletter",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["reset", "monthly review", "checklist", "workflow"],
        featured: false,
        uniquenessScore: 76,
      },
      {
        title: "SOP for Posting Without Chaos",
        description:
          "Share a simple pre-publish checklist so posting no longer depends on memory or panic.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["sop", "publishing", "checklist", "ops"],
        featured: false,
        uniquenessScore: 77,
      },
      {
        title: "First Hire Readiness Score",
        description:
          "Use a scorecard to show when someone is truly ready to bring in editing or admin help.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 35,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        audience: "Convert",
        goals: ["Sell Offer", "Build Authority"],
        tags: ["hiring", "readiness", "operations", "scale"],
        featured: false,
        uniquenessScore: 86,
      },
      {
        title: "Asset Naming System",
        description:
          "Explain a file naming convention that stops footage, graphics, and exports from turning messy.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 10,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: true,
        tags: ["file naming", "assets", "organization", "workflow"],
        featured: false,
        uniquenessScore: 74,
      },
      {
        title: "Idea Inbox Workflow",
        description:
          "Show how random notes move into themes, then into actual scheduled content with less friction.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 25,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["ideas", "capture", "workflow", "planning"],
        featured: false,
        uniquenessScore: 82,
      },
      {
        title: "My Four-Block Creator Week",
        description:
          "Break the week into planning, filming, editing, and distribution so the workload feels manageable.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 15,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        goals: ["Improve Consistency", "Grow Audience"],
        tags: ["weekly plan", "time management", "creator week", "systems"],
        featured: false,
        uniquenessScore: 85,
      },
    ],
  },
  {
    niche: "Community Building",
    audience: "Nurture",
    goals: ["Increase Engagement", "Build Authority"],
    ideas: [
      {
        title: "Better Comment Prompts",
        description:
          "Replace weak engagement bait with prompts that create more natural and useful replies.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 10,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["comments", "engagement", "community", "prompts"],
        featured: true,
        uniquenessScore: 90,
      },
      {
        title: "Subscriber Q&A Live",
        description:
          "Run a visible Q&A session that surfaces real audience pain points and doubles as idea research.",
        format: "Live",
        difficulty: "Medium",
        filmingMinutes: 45,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["q&a", "live", "community", "questions"],
        featured: false,
        uniquenessScore: 86,
      },
      {
        title: "DM Questions Into Product Research",
        description:
          "Show how recurring direct messages can shape content, offers, and messaging with less guessing.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Convert",
        goals: ["Sell Offer", "Build Authority"],
        tags: ["dms", "research", "offers", "messaging"],
        featured: true,
        uniquenessScore: 92,
      },
      {
        title: "Community Poll That Actually Helps",
        description:
          "Design poll questions that create direction and insight instead of random vanity interaction.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["polls", "community", "research", "engagement"],
        featured: false,
        uniquenessScore: 84,
      },
      {
        title: "Weekly Challenge for Followers",
        description:
          "Create a recurring challenge that gives the audience a reason to participate, share, and return.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        goals: ["Increase Engagement", "Improve Consistency"],
        tags: ["challenge", "followers", "retention", "community"],
        featured: false,
        uniquenessScore: 83,
      },
      {
        title: "Thank-You Post That Builds Loyalty",
        description:
          "Turn a simple gratitude post into something specific enough that followers feel genuinely seen.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 10,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: true,
        tags: ["gratitude", "loyalty", "community", "retention"],
        featured: false,
        uniquenessScore: 75,
      },
      {
        title: "How I Onboard New Subscribers",
        description:
          "Teach creators how to orient new followers with a starter path instead of hoping they figure it out.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 30,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["onboarding", "subscribers", "community", "journey"],
        featured: false,
        uniquenessScore: 82,
      },
      {
        title: "Reply Strategy for the First Hour",
        description:
          "Share a first-hour response routine that helps posts build stronger conversation momentum.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["replying", "first hour", "engagement", "community"],
        featured: false,
        uniquenessScore: 81,
      },
      {
        title: "Audience Wins Showcase",
        description:
          "Feature follower progress to strengthen community identity while still teaching through examples.",
        format: "Newsletter",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["wins", "showcase", "community", "proof"],
        featured: false,
        uniquenessScore: 78,
      },
      {
        title: "A Community Series With Inside Jokes",
        description:
          "Build a recurring format that gives loyal followers something recognizable to come back for.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 15,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        goals: ["Increase Engagement", "Grow Audience"],
        audience: "Attract",
        tags: ["series", "inside jokes", "retention", "identity"],
        featured: false,
        uniquenessScore: 87,
      },
    ],
  },
  {
    niche: "Audience Research",
    audience: "Convert",
    goals: ["Build Authority", "Sell Offer"],
    ideas: [
      {
        title: "Content Ideas Hidden in Your Analytics",
        description:
          "Show how high-retention topics and repeated searches can drive the next content batch.",
        format: "Carousel",
        difficulty: "Medium",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["analytics", "ideas", "research", "retention"],
        featured: true,
        uniquenessScore: 90,
      },
      {
        title: "How I Read Comment Language",
        description:
          "Break down why exact audience wording is often better than rewriting everything into polished jargon.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["comments", "language", "research", "messaging"],
        featured: false,
        uniquenessScore: 84,
      },
      {
        title: "Survey Questions That Reveal Buying Intent",
        description:
          "Show how to ask questions that uncover urgency, obstacles, and what people already tried.",
        format: "Carousel",
        difficulty: "Medium",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["survey", "buying intent", "research", "offers"],
        featured: true,
        uniquenessScore: 93,
      },
      {
        title: "The KPI I Ignore on Purpose",
        description:
          "Challenge a popular metric and explain why it does not help you make better content decisions.",
        format: "Newsletter",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Nurture",
        goals: ["Build Authority", "Increase Engagement"],
        tags: ["kpi", "analytics", "focus", "decision making"],
        featured: false,
        uniquenessScore: 80,
      },
      {
        title: "Three Questions to Ask Before You Build",
        description:
          "Help creators validate demand before investing more time into a product, series, or resource.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 10,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["validation", "questions", "research", "build"],
        featured: false,
        uniquenessScore: 82,
      },
      {
        title: "Voice-of-Customer Swipe Board",
        description:
          "Show the system you use to collect recurring phrases from comments, DMs, and calls.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 30,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["voice of customer", "research", "swipe file", "messaging"],
        featured: false,
        uniquenessScore: 86,
      },
      {
        title: "How to Spot a Real Pain Point",
        description:
          "Compare vague audience desires with sharper pain signals that are easier to build around.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["pain points", "research", "offers", "clarity"],
        featured: false,
        uniquenessScore: 81,
      },
      {
        title: "Call Notes to Better Messaging",
        description:
          "Turn discovery call notes into content and sales messaging instead of leaving them buried in docs.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 28,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Convert",
        tags: ["call notes", "messaging", "research", "offers"],
        featured: false,
        uniquenessScore: 85,
      },
      {
        title: "The Audience Signal Board I Review Monthly",
        description:
          "Build a board around repeated objections, desired outcomes, and language patterns over time.",
        format: "Newsletter",
        difficulty: "Medium",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Nurture",
        goals: ["Build Authority", "Improve Consistency"],
        tags: ["board", "signals", "research", "monthly review"],
        featured: false,
        uniquenessScore: 79,
      },
      {
        title: "When Not to Trust a Poll",
        description:
          "Explain why audience polls are useful directionally but dangerous when they replace judgment.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["polls", "research", "judgment", "content strategy"],
        featured: false,
        uniquenessScore: 83,
      },
    ],
  },
  {
    niche: "Personal Branding",
    audience: "Attract",
    goals: ["Grow Audience", "Build Authority"],
    ideas: [
      {
        title: "The One-Sentence Positioning Test",
        description:
          "Help creators tighten their profile messaging with a simple clarity test anyone can repeat.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["positioning", "branding", "bio", "clarity"],
        featured: true,
        uniquenessScore: 89,
      },
      {
        title: "The Purpose of Life Is Not What You Think",
        description:
          "Use a philosophical hook to reveal the worldview behind your brand and turn it into a more memorable teaching angle.",
        format: "YouTube",
        difficulty: "High",
        filmingMinutes: 50,
        editingEffort: "High",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["teaching", "specificity", "voice", "branding"],
        featured: true,
        uniquenessScore: 99,
      },
      {
        title: "Profile Rewrite Before and After",
        description:
          "Take a vague creator bio and rewrite it so the value and audience are obvious in seconds.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["profile", "bio", "positioning", "before after"],
        featured: false,
        uniquenessScore: 84,
      },
      {
        title: "The Story I Keep Repeating On Purpose",
        description:
          "Show how a recurring founder or creator story can anchor trust without sounding repetitive.",
        format: "Newsletter",
        difficulty: "Medium",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Nurture",
        tags: ["storytelling", "trust", "brand narrative", "email"],
        featured: false,
        uniquenessScore: 81,
      },
      {
        title: "Three Opinions That Make You Memorable",
        description:
          "Use point-of-view examples to show why useful disagreement often creates stronger brand recall.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 10,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["opinions", "voice", "branding", "memorability"],
        featured: false,
        uniquenessScore: 86,
      },
      {
        title: "My Creator Brand Moodboard",
        description:
          "Walk through visual references, repeated motifs, and words that keep your content world coherent.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 30,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["moodboard", "visual identity", "brand", "creative direction"],
        featured: false,
        uniquenessScore: 83,
      },
      {
        title: "The Expert Trap: Looking Too Polished",
        description:
          "Explain when hyper-polished positioning can lower relatability and how to rebalance it.",
        format: "Carousel",
        difficulty: "Medium",
        filmingMinutes: 0,
        editingEffort: "Medium",
        engagementPotential: "High",
        trendFriendly: false,
        tags: ["positioning", "expert", "relatability", "trust"],
        featured: false,
        uniquenessScore: 87,
      },
      {
        title: "Signature Phrases for Your Content World",
        description:
          "Show how recurring phrases can act like micro-brand assets across shorts, captions, and emails.",
        format: "Carousel",
        difficulty: "Low",
        filmingMinutes: 0,
        editingEffort: "Low",
        engagementPotential: "Medium",
        trendFriendly: false,
        tags: ["phrases", "brand voice", "consistency", "messaging"],
        featured: false,
        uniquenessScore: 80,
      },
      {
        title: "The About Page Most Creators Skip",
        description:
          "Teach a simple about-page structure that makes expertise and next steps easier to trust.",
        format: "YouTube",
        difficulty: "Medium",
        filmingMinutes: 25,
        editingEffort: "Medium",
        engagementPotential: "Medium",
        trendFriendly: false,
        audience: "Convert",
        goals: ["Build Authority", "Sell Offer"],
        tags: ["about page", "website", "trust", "positioning"],
        featured: false,
        uniquenessScore: 82,
      },
      {
        title: "What I Want People to Say About My Work",
        description:
          "Reverse-engineer a stronger creator brand by starting with the impression you want to create.",
        format: "Shorts",
        difficulty: "Low",
        filmingMinutes: 12,
        editingEffort: "Low",
        engagementPotential: "High",
        trendFriendly: true,
        tags: ["perception", "branding", "message", "clarity"],
        featured: false,
        uniquenessScore: 85,
      },
    ],
  },
];

const GENERATED_TITLE_FORMS = [
  "What Nobody Tells You About {term}",
  "The {term} Reset I Would Start Today",
  "Why {term} Matters More Than You Think",
  "If I Had To Rebuild {term} From Zero",
  "The Fastest Way To Make {term} Click",
];

const GENERATED_DESCRIPTION_FORMS = [
  "Break down why {promise}, and turn it into a sharp, practical takeaway people can use immediately.",
  "Package {term} as a cleaner framework that helps show how {promise}.",
  "Use a stronger point of view to explain why {promise} without sounding generic or overproduced.",
  "Turn {term} into a step-by-step angle that makes it obvious how {promise}.",
  "Lead with a punchy example so viewers quickly understand why {promise}.",
];

const GENERATED_IDEA_BLUEPRINTS = {
  "Creator Education": {
    formats: ["Carousel", "YouTube", "Shorts", "YouTube", "Newsletter"],
    topics: [
      ["Creator Identity", "new creators stop copying and start sounding like themselves", ["identity", "voice", "clarity"]],
      ["Publishing Rhythm", "creators stay consistent without burning out by week two", ["consistency", "workflow", "energy"]],
      ["Taste Building", "creators choose stronger ideas before they ever start filming", ["taste", "judgment", "creative growth"]],
    ],
  },
  "YouTube Growth": {
    formats: ["YouTube", "Carousel", "Shorts", "YouTube", "Live"],
    topics: [
      ["Thumbnail Logic", "click-through becomes a lever instead of a guessing game", ["thumbnail", "ctr", "packaging"]],
      ["Audience Fit", "channels get clearer about who they actually serve", ["audience", "positioning", "clarity"]],
      ["Topic Packaging", "good ideas stop dying before the first impression", ["topics", "packaging", "clicks"]],
    ],
  },
  "Short-Form Strategy": {
    formats: ["Carousel", "Shorts", "YouTube", "Shorts", "Carousel"],
    topics: [
      ["Hook Design", "openings earn attention without feeling fake or frantic", ["hooks", "attention", "openings"]],
      ["Replay Loops", "shorts create rewatch moments on purpose instead of by luck", ["replays", "retention", "shorts"]],
      ["Comment Mining", "replies turn into repeatable content systems instead of random posts", ["comments", "ideas", "systems"]],
    ],
  },
  "Video Editing": {
    formats: ["YouTube", "Shorts", "YouTube", "Carousel", "Live"],
    topics: [
      ["Pacing", "edits feel alive without making the viewer feel rushed", ["pacing", "timing", "editing"]],
      ["Retention Cuts", "every trim increases clarity instead of just making things shorter", ["retention", "cuts", "clarity"]],
      ["B-Roll Systems", "talking-head videos stop feeling flat and repetitive", ["b-roll", "visuals", "workflow"]],
    ],
  },
  "Monetization": {
    formats: ["Carousel", "YouTube", "Shorts", "Newsletter", "YouTube"],
    topics: [
      ["Offer Positioning", "small creators sell something believable before they try selling something big", ["offers", "positioning", "sales"]],
      ["Trust Ladders", "audiences warm up before the pitch ever arrives", ["trust", "funnel", "conversion"]],
      ["Price Framing", "offers feel obvious instead of awkward or overpriced", ["pricing", "framing", "value"]],
    ],
  },
  "Email Marketing": {
    formats: ["Newsletter", "Carousel", "Shorts", "Newsletter", "YouTube"],
    topics: [
      ["Welcome Emails", "new subscribers care faster instead of quietly disappearing", ["welcome email", "onboarding", "retention"]],
      ["Subject Lines", "emails open because curiosity feels honest instead of manipulative", ["subject lines", "open rates", "copy"]],
      ["Soft Selling", "newsletters convert without sounding needy or desperate", ["soft sell", "email", "conversion"]],
    ],
  },
  "Brand Deals": {
    formats: ["YouTube", "Carousel", "Shorts", "YouTube", "Newsletter"],
    topics: [
      ["Outreach Framing", "pitches sound valuable instead of begging for attention", ["outreach", "pitch", "brand deals"]],
      ["Proof Stacking", "creators look safer to hire even before a sponsor call", ["proof", "trust", "case studies"]],
      ["Sponsored Storytelling", "ads feel native to your content instead of bolted on", ["sponsored", "storytelling", "integration"]],
    ],
  },
  Repurposing: {
    formats: ["Carousel", "YouTube", "Shorts", "Carousel", "Live"],
    topics: [
      ["Content Atomization", "one long piece turns into a week of assets instead of one upload", ["repurposing", "assets", "systems"]],
      ["Asset Libraries", "old ideas stay useful longer instead of dying after one post", ["libraries", "content bank", "workflow"]],
      ["Remix Systems", "creators stop starting from blank pages every week", ["remix", "workflow", "efficiency"]],
    ],
  },
  "Creator Systems": {
    formats: ["Carousel", "YouTube", "Newsletter", "Carousel", "Shorts"],
    topics: [
      ["Capture Systems", "ideas stop disappearing just because the timing is inconvenient", ["capture", "notes", "ideas"]],
      ["Batch Planning", "creators make once and ship longer without losing quality", ["batching", "planning", "systems"]],
      ["Review Loops", "creators improve with evidence instead of vibes", ["review", "feedback", "iteration"]],
    ],
  },
  "Community Building": {
    formats: ["Live", "Carousel", "Shorts", "YouTube", "Newsletter"],
    topics: [
      ["Ritual Design", "audiences feel like insiders instead of passive viewers", ["rituals", "community", "loyalty"]],
      ["Participation Prompts", "community members talk back more often and more thoughtfully", ["engagement", "prompts", "conversation"]],
      ["Creator Closeness", "followers feel seen without forcing one-to-one burnout", ["closeness", "audience", "boundaries"]],
    ],
  },
  "Audience Research": {
    formats: ["Carousel", "YouTube", "Shorts", "Newsletter", "YouTube"],
    topics: [
      ["Customer Language", "titles start sounding like the audience instead of the creator", ["voice of customer", "research", "titles"]],
      ["Silent Objections", "creators answer doubts before skeptical comments ever appear", ["objections", "messaging", "clarity"]],
      ["Pattern Spotting", "better ideas come from repeated signals instead of random inspiration", ["patterns", "signals", "research"]],
    ],
  },
  "Personal Branding": {
    formats: ["YouTube", "Carousel", "Shorts", "YouTube", "Newsletter"],
    topics: [
      ["Worldview Hooks", "big beliefs make creators memorable beyond their niche", ["worldview", "beliefs", "brand"]],
      ["Personal Mythology", "stories reinforce positioning instead of just sounding personal", ["stories", "mythology", "brand narrative"]],
      ["Perception Design", "audiences remember the right thing when they think about your work", ["perception", "positioning", "branding"]],
    ],
  },
};

function fillGeneratedTemplate(template, term, promise) {
  return template.replaceAll("{term}", term).replaceAll("{promise}", promise);
}

function getGeneratedProfile(format, variantIndex) {
  if (format === "Carousel") {
    return {
      difficulty: variantIndex % 2 === 0 ? "Low" : "Medium",
      filmingMinutes: 0,
      editingEffort: variantIndex % 3 === 0 ? "Medium" : "Low",
      engagementPotential: "High",
      trendFriendly: variantIndex % 2 !== 0,
    };
  }

  if (format === "Shorts") {
    return {
      difficulty: "Low",
      filmingMinutes: 10 + (variantIndex % 3) * 4,
      editingEffort: variantIndex % 2 === 0 ? "Low" : "Medium",
      engagementPotential: "High",
      trendFriendly: true,
    };
  }

  if (format === "Newsletter") {
    return {
      difficulty: variantIndex % 2 === 0 ? "Low" : "Medium",
      filmingMinutes: 0,
      editingEffort: variantIndex % 2 === 0 ? "Low" : "Medium",
      engagementPotential: variantIndex % 2 === 0 ? "Medium" : "High",
      trendFriendly: false,
    };
  }

  if (format === "Live") {
    return {
      difficulty: "Medium",
      filmingMinutes: 35 + (variantIndex % 2) * 12,
      editingEffort: "Low",
      engagementPotential: "High",
      trendFriendly: variantIndex % 2 === 0,
    };
  }

  return {
    difficulty: variantIndex % 2 === 0 ? "Medium" : "High",
    filmingMinutes: 28 + (variantIndex % 3) * 8,
    editingEffort: variantIndex % 2 === 0 ? "Medium" : "High",
    engagementPotential: "High",
    trendFriendly: false,
  };
}

function buildGeneratedIdeas(collection, blueprint) {
  if (!blueprint) {
    return [];
  }

  return blueprint.topics.flatMap(([term, promise, tags], topicIndex) =>
    GENERATED_TITLE_FORMS.map((titleTemplate, formIndex) => {
      const format = blueprint.formats[formIndex];
      const profile = getGeneratedProfile(format, topicIndex + formIndex);

      return {
        title: fillGeneratedTemplate(titleTemplate, term, promise),
        description: fillGeneratedTemplate(GENERATED_DESCRIPTION_FORMS[formIndex], term, promise),
        format,
        difficulty: profile.difficulty,
        filmingMinutes: profile.filmingMinutes,
        editingEffort: profile.editingEffort,
        engagementPotential: profile.engagementPotential,
        trendFriendly: profile.trendFriendly,
        tags: [...new Set([...tags, format.toLowerCase(), term.toLowerCase()])].slice(0, 4),
        featured: false,
        uniquenessScore: 82 + topicIndex * 5 + formIndex,
      };
    }),
  );
}

const EXPANDED_IDEA_COLLECTIONS = IDEA_COLLECTIONS.map((collection) => ({
  ...collection,
  ideas: [...collection.ideas, ...buildGeneratedIdeas(collection, GENERATED_IDEA_BLUEPRINTS[collection.niche])],
}));

function slugifyCatalogValue(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

const CONTENT_IDEAS = EXPANDED_IDEA_COLLECTIONS.flatMap((collection) =>
  collection.ideas.map((idea, index) => ({
    id: `${slugifyCatalogValue(collection.niche)}-${index + 1}`,
    niche: collection.niche,
    audience: idea.audience || collection.audience,
    goals: idea.goals || collection.goals,
    ...idea,
  })),
);

window.IDEA_COLLECTIONS = EXPANDED_IDEA_COLLECTIONS;
window.CONTENT_IDEAS = CONTENT_IDEAS;
